### ISSUE TITLE
"TypeError: this.options.position is undefined" if using the default config

### ISSUE THREAD

**Issue by MarcelKr** [thomasschwarz96/grav-plugin-simple-cookie#2] opened 2020-01-03 17:12 UTC
If using the default config (enabled: true, custom: false) the error is displayed in the console and the consent popup isn't shown
```TypeError: this.options.position is undefined - cookieconsent.min.js:1:5345```

Only if copying the additional options to the config file the plugin works as expected.

Grav version 1.6.19
Simple Cookie version 0.1.2

**Comment by qw3rtty** [comment] 2020-01-04 13:32
Thanks for your report.
I will fix it and let you know when i am done.

**Comment by qw3rtty** [comment] 2020-01-05 11:52
Hey @MarcelKr, 
i can't reproduce the error.

I made a complete new Install of Grav CMS and installed the Simple-Cookie plugin.
I checked the default config file and everything works fine.

Maybe you have a Plugin installed that creates the error?
Can you give me more details?

**Comment by MarcelKr** [comment] 2020-01-05 14:56
I'll give it a try in the next few days and report back

**Comment by qw3rtty** [comment] 2020-01-20 23:26
@MarcelKr 
Do you have more details for me?
Otherwise i will close this issue.
Thx.

**Comment by MarcelKr** [comment] 2020-01-21 08:30
Also with a fresh install of grav I get the error ``TypeError: this.options.position is undefinedcookieconsent.min.js:1:5345``.
Either by providing no user config file in ``user/config/plugins`` or with the plugin's config file copied to ``user/config/plugins``.

The config file only contains the default settings:

    enabled: true
    custom: false

As soon as I add ``position: bottom-right`` to the config, the error changes to ``TypeError: e is undefinedcookieconsent.min.js:1:1302``

As soon as I add ``palette: gray`` the errors are gone and the consent windows shows up.

So a minimal working config seems to be:

    enabled: true
    custom: false
    position: bottom-right
    palette: gray

**Comment by qw3rtty** [comment] 2020-01-21 18:01
@MarcelKr 
Thanks for your fast reply!
I could reproduce the error and i fixed it.
The update should be available soon on grav.

**Closed as completed** 2020-01-22 06:41 UTC
Labels: bug
